<#
.Description
IsEven, but in the worst possible way.
#>

param (
    $In = $1
)

if ($In -eq 0) {$true}
elseif ($In -eq 1) {$False}
elseif ($In -eq 2) {$True}
elseif ($In -eq 3) {$False}
elseif ($In -eq 4) {$True}
elseif ($In -eq 5) {$False}
elseif ($In -eq 6) {$True}
elseif ($In -eq 7) {$False}
elseif ($In -eq 8) {$True}
elseif ($In -eq 9) {$False}
elseif ($In -eq 10) {$True}
elseif ($In -eq 11) {$False}
elseif ($In -eq 12) {$True}
elseif ($In -eq 13) {$False}
elseif ($In -eq 14) {$True}
elseif ($In -eq 15) {$False}
elseif ($In -eq 16) {$True}
elseif ($In -eq 17) {$False}
elseif ($In -eq 18) {$True}
elseif ($In -eq 19) {$False}
elseif ($In -eq 20) {$True}
elseif ($In -eq 21) {$False}
elseif ($In -eq 22) {$True}
elseif ($In -eq 23) {$False}
elseif ($In -eq 24) {$True}
elseif ($In -eq 25) {$False}
elseif ($In -eq 26) {$True}
elseif ($In -eq 27) {$False}
elseif ($In -eq 28) {$True}
elseif ($In -eq 29) {$False}
elseif ($In -eq 30) {$True}
elseif ($In -eq 31) {$False}
elseif ($In -eq 32) {$True}
elseif ($In -eq 33) {$False}
elseif ($In -eq 34) {$True}
elseif ($In -eq 35) {$False}
elseif ($In -eq 36) {$True}
elseif ($In -eq 37) {$False}
elseif ($In -eq 38) {$True}
elseif ($In -eq 39) {$False}
elseif ($In -eq 40) {$True}
elseif ($In -eq 41) {$False}
elseif ($In -eq 42) {$True}
elseif ($In -eq 43) {$False}
elseif ($In -eq 44) {$True}
elseif ($In -eq 45) {$False}
elseif ($In -eq 46) {$True}
elseif ($In -eq 47) {$False}
elseif ($In -eq 48) {$True}
elseif ($In -eq 49) {$False}
elseif ($In -eq 50) {$True}
elseif ($In -eq 51) {$False}
elseif ($In -eq 52) {$True}
elseif ($In -eq 53) {$False}
elseif ($In -eq 54) {$True}
elseif ($In -eq 55) {$False}
elseif ($In -eq 56) {$True}
elseif ($In -eq 57) {$False}
elseif ($In -eq 58) {$True}
elseif ($In -eq 59) {$False}
elseif ($In -eq 60) {$True}
elseif ($In -eq 61) {$False}
elseif ($In -eq 62) {$True}
elseif ($In -eq 63) {$False}
elseif ($In -eq 64) {$True}
elseif ($In -eq 65) {$False}
elseif ($In -eq 66) {$True}
elseif ($In -eq 67) {$False}
elseif ($In -eq 68) {$True}
elseif ($In -eq 69) {$False}
elseif ($In -eq 70) {$True}
elseif ($In -eq 71) {$False}
elseif ($In -eq 72) {$True}
elseif ($In -eq 73) {$False}
elseif ($In -eq 74) {$True}
elseif ($In -eq 75) {$False}
elseif ($In -eq 76) {$True}
elseif ($In -eq 77) {$False}
elseif ($In -eq 78) {$True}
elseif ($In -eq 79) {$False}
elseif ($In -eq 80) {$True}
elseif ($In -eq 81) {$False}
elseif ($In -eq 82) {$True}
elseif ($In -eq 83) {$False}
elseif ($In -eq 84) {$True}
elseif ($In -eq 85) {$False}
elseif ($In -eq 86) {$True}
elseif ($In -eq 87) {$False}
elseif ($In -eq 88) {$True}
elseif ($In -eq 89) {$False}
elseif ($In -eq 90) {$True}
elseif ($In -eq 91) {$False}
elseif ($In -eq 92) {$True}
elseif ($In -eq 93) {$False}
elseif ($In -eq 94) {$True}
elseif ($In -eq 95) {$False}
elseif ($In -eq 96) {$True}
elseif ($In -eq 97) {$False}
elseif ($In -eq 98) {$True}
elseif ($In -eq 99) {$False}
elseif ($In -eq 100) {$True}
elseif ($In -eq 101) {$False}
elseif ($In -eq 102) {$True}
elseif ($In -eq 103) {$False}
elseif ($In -eq 104) {$True}
elseif ($In -eq 105) {$False}
elseif ($In -eq 106) {$True}
elseif ($In -eq 107) {$False}
elseif ($In -eq 108) {$True}
elseif ($In -eq 109) {$False}
elseif ($In -eq 110) {$True}
elseif ($In -eq 111) {$False}
elseif ($In -eq 112) {$True}
elseif ($In -eq 113) {$False}
elseif ($In -eq 114) {$True}
elseif ($In -eq 115) {$False}
elseif ($In -eq 116) {$True}
elseif ($In -eq 117) {$False}
elseif ($In -eq 118) {$True}
elseif ($In -eq 119) {$False}
elseif ($In -eq 120) {$True}
elseif ($In -eq 121) {$False}
elseif ($In -eq 122) {$True}
elseif ($In -eq 123) {$False}
elseif ($In -eq 124) {$True}
elseif ($In -eq 125) {$False}
elseif ($In -eq 126) {$True}
elseif ($In -eq 127) {$False}
elseif ($In -eq 128) {$True}
elseif ($In -eq 129) {$False}
elseif ($In -eq 130) {$True}
elseif ($In -eq 131) {$False}
elseif ($In -eq 132) {$True}
elseif ($In -eq 133) {$False}
elseif ($In -eq 134) {$True}
elseif ($In -eq 135) {$False}
elseif ($In -eq 136) {$True}
elseif ($In -eq 137) {$False}
elseif ($In -eq 138) {$True}
elseif ($In -eq 139) {$False}
elseif ($In -eq 140) {$True}
elseif ($In -eq 141) {$False}
elseif ($In -eq 142) {$True}
elseif ($In -eq 143) {$False}
elseif ($In -eq 144) {$True}
elseif ($In -eq 145) {$False}
elseif ($In -eq 146) {$True}
elseif ($In -eq 147) {$False}
elseif ($In -eq 148) {$True}
elseif ($In -eq 149) {$False}
elseif ($In -eq 150) {$True}
elseif ($In -eq 151) {$False}
elseif ($In -eq 152) {$True}
elseif ($In -eq 153) {$False}
elseif ($In -eq 154) {$True}
elseif ($In -eq 155) {$False}
elseif ($In -eq 156) {$True}
elseif ($In -eq 157) {$False}
elseif ($In -eq 158) {$True}
elseif ($In -eq 159) {$False}
elseif ($In -eq 160) {$True}
elseif ($In -eq 161) {$False}
elseif ($In -eq 162) {$True}
elseif ($In -eq 163) {$False}
elseif ($In -eq 164) {$True}
elseif ($In -eq 165) {$False}
elseif ($In -eq 166) {$True}
elseif ($In -eq 167) {$False}
elseif ($In -eq 168) {$True}
elseif ($In -eq 169) {$False}
elseif ($In -eq 170) {$True}
elseif ($In -eq 171) {$False}
elseif ($In -eq 172) {$True}
elseif ($In -eq 173) {$False}
elseif ($In -eq 174) {$True}
elseif ($In -eq 175) {$False}
elseif ($In -eq 176) {$True}
elseif ($In -eq 177) {$False}
elseif ($In -eq 178) {$True}
elseif ($In -eq 179) {$False}
elseif ($In -eq 180) {$True}
elseif ($In -eq 181) {$False}
elseif ($In -eq 182) {$True}
elseif ($In -eq 183) {$False}
elseif ($In -eq 184) {$True}
elseif ($In -eq 185) {$False}
elseif ($In -eq 186) {$True}
elseif ($In -eq 187) {$False}
elseif ($In -eq 188) {$True}
elseif ($In -eq 189) {$False}
elseif ($In -eq 190) {$True}
elseif ($In -eq 191) {$False}
elseif ($In -eq 192) {$True}
elseif ($In -eq 193) {$False}
elseif ($In -eq 194) {$True}
elseif ($In -eq 195) {$False}
elseif ($In -eq 196) {$True}
elseif ($In -eq 197) {$False}
elseif ($In -eq 198) {$True}
elseif ($In -eq 199) {$False}
elseif ($In -eq 200) {$True}
elseif ($In -eq 201) {$False}
elseif ($In -eq 202) {$True}
elseif ($In -eq 203) {$False}
elseif ($In -eq 204) {$True}
elseif ($In -eq 205) {$False}
elseif ($In -eq 206) {$True}
elseif ($In -eq 207) {$False}
elseif ($In -eq 208) {$True}
elseif ($In -eq 209) {$False}
elseif ($In -eq 210) {$True}
elseif ($In -eq 211) {$False}
elseif ($In -eq 212) {$True}
elseif ($In -eq 213) {$False}
elseif ($In -eq 214) {$True}
elseif ($In -eq 215) {$False}
elseif ($In -eq 216) {$True}
elseif ($In -eq 217) {$False}
elseif ($In -eq 218) {$True}
elseif ($In -eq 219) {$False}
elseif ($In -eq 220) {$True}
elseif ($In -eq 221) {$False}
elseif ($In -eq 222) {$True}
elseif ($In -eq 223) {$False}
elseif ($In -eq 224) {$True}
elseif ($In -eq 225) {$False}
elseif ($In -eq 226) {$True}
elseif ($In -eq 227) {$False}
elseif ($In -eq 228) {$True}
elseif ($In -eq 229) {$False}
elseif ($In -eq 230) {$True}
elseif ($In -eq 231) {$False}
elseif ($In -eq 232) {$True}
elseif ($In -eq 233) {$False}
elseif ($In -eq 234) {$True}
elseif ($In -eq 235) {$False}
elseif ($In -eq 236) {$True}
elseif ($In -eq 237) {$False}
elseif ($In -eq 238) {$True}
elseif ($In -eq 239) {$False}
elseif ($In -eq 240) {$True}
elseif ($In -eq 241) {$False}
elseif ($In -eq 242) {$True}
elseif ($In -eq 243) {$False}
elseif ($In -eq 244) {$True}
elseif ($In -eq 245) {$False}
elseif ($In -eq 246) {$True}
elseif ($In -eq 247) {$False}
elseif ($In -eq 248) {$True}
elseif ($In -eq 249) {$False}
elseif ($In -eq 250) {$True}
elseif ($In -eq 251) {$False}
elseif ($In -eq 252) {$True}
elseif ($In -eq 253) {$False}
elseif ($In -eq 254) {$True}
elseif ($In -eq 255) {$False}
elseif ($In -eq 256) {$True}
else {Write-Error "Number is waay too big!"}
# Operation took 2.3082085 Seconds.
