function test-one([int]$int){if(1-eq$int){return $int%2-eq0}}
function test-two([int]$int){if(2-eq$int){return $int%2-eq0}}
function test-three([int]$int){if(3-eq$int){return $int%2-eq0}}
function test-four([int]$int){if(4-eq$int){return $int%2-eq0}}
function test-five([int]$int){if(5-eq$int){return $int%2-eq0}}
function test-six([int]$int){if(6-eq$int){return $int%2-eq0}}
function test-seven([int]$int){if(7-eq$int){return $int%2-eq0}}
function test-eight([int]$int){if(8-eq$int){return $int%2-eq0}}
function test-nine([int]$int){if(9-eq$int){return $int%2-eq0}}
function test-ten([int]$int){if(10-eq$int){return $int%2-eq0}}
function test-eleven([int]$int){if(11-eq$int){return $int%2-eq0}}
function test-twelve([int]$int){if(12-eq$int){return $int%2-eq0}}
function test-thirteen([int]$int){if(13-eq$int){return $int%2-eq0}}
function test-fourteen([int]$int){if(14-eq$int){return $int%2-eq0}}
function test-fifteen([int]$int){if(15-eq$int){return $int%2-eq0}}
function test-sixteen([int]$int){if(16-eq$int){return $int%2-eq0}}
function test-seventeen([int]$int){if(17-eq$int){return $int%2-eq0}}
function test-eighteen([int]$int){if(18-eq$int){return $int%2-eq0}}
function test-nineteen([int]$int){if(19-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(20-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(21-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(22-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(23-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(24-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(25-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(26-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(27-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(28-eq$int){return $int%2-eq0}}
function test-twenty([int]$int){if(29-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(30-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(31-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(32-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(33-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(34-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(35-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(36-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(37-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(38-eq$int){return $int%2-eq0}}
function test-thirty([int]$int){if(39-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(40-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(41-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(42-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(43-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(44-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(45-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(46-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(47-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(48-eq$int){return $int%2-eq0}}
function test-forty([int]$int){if(49-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(50-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(51-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(52-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(53-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(54-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(55-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(56-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(57-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(58-eq$int){return $int%2-eq0}}
function test-fifty([int]$int){if(59-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(60-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(61-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(62-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(63-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(64-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(65-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(66-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(67-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(68-eq$int){return $int%2-eq0}}
function test-sixty([int]$int){if(69-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(70-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(71-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(72-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(73-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(74-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(75-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(76-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(77-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(78-eq$int){return $int%2-eq0}}
function test-seventy([int]$int){if(79-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(80-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(81-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(82-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(83-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(84-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(85-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(86-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(87-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(88-eq$int){return $int%2-eq0}}
function test-eighty([int]$int){if(89-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(90-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(91-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(92-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(93-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(94-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(95-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(96-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(97-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(98-eq$int){return $int%2-eq0}}
function test-ninety([int]$int){if(99-eq$int){return $int%2-eq0}}
function test-one-hundred([int]$int){if(100-eq$int){return $int%2-eq0}}
function test-one-hundred-and-one([int]$int){if(101-eq$int){return $int%2-eq0}}
function test-one-hundred-and-two([int]$int){if(102-eq$int){return $int%2-eq0}}
function test-one-hundred-and-three([int]$int){if(103-eq$int){return $int%2-eq0}}
function test-one-hundred-and-four([int]$int){if(104-eq$int){return $int%2-eq0}}
function test-one-hundred-and-five([int]$int){if(105-eq$int){return $int%2-eq0}}
function test-one-hundred-and-six([int]$int){if(106-eq$int){return $int%2-eq0}}
function test-one-hundred-and-seven([int]$int){if(107-eq$int){return $int%2-eq0}}
function test-one-hundred-and-eight([int]$int){if(108-eq$int){return $int%2-eq0}}
function test-one-hundred-and-nine([int]$int){if(109-eq$int){return $int%2-eq0}}
function test-one-hundred-ten([int]$int){if(110-eq$int){return $int%2-eq0}}
function test-one-hundred-eleven([int]$int){if(111-eq$int){return $int%2-eq0}}
function test-one-hundred-twelve([int]$int){if(112-eq$int){return $int%2-eq0}}
function test-one-hundred-thirteen([int]$int){if(113-eq$int){return $int%2-eq0}}
function test-one-hundred-fourteen([int]$int){if(114-eq$int){return $int%2-eq0}}
function test-one-hundred-fifteen([int]$int){if(115-eq$int){return $int%2-eq0}}
function test-one-hundred-sixteen([int]$int){if(116-eq$int){return $int%2-eq0}}
function test-one-hundred-seventeen([int]$int){if(117-eq$int){return $int%2-eq0}}
function test-one-hundred-eighteen([int]$int){if(118-eq$int){return $int%2-eq0}}
function test-one-hundred-nineteen([int]$int){if(119-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty([int]$int){if(120-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-one([int]$int){if(121-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-two([int]$int){if(122-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-three([int]$int){if(123-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-four([int]$int){if(124-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-five([int]$int){if(125-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-six([int]$int){if(126-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-seven([int]$int){if(127-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-eight([int]$int){if(128-eq$int){return $int%2-eq0}}
function test-one-hundred-twenty-nine([int]$int){if(129-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty([int]$int){if(130-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-one([int]$int){if(131-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-two([int]$int){if(132-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-three([int]$int){if(133-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-four([int]$int){if(134-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-five([int]$int){if(135-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-six([int]$int){if(136-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-seven([int]$int){if(137-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-eight([int]$int){if(138-eq$int){return $int%2-eq0}}
function test-one-hundred-thirty-nine([int]$int){if(139-eq$int){return $int%2-eq0}}
function test-one-hundred-forty([int]$int){if(140-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-one([int]$int){if(141-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-two([int]$int){if(142-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-three([int]$int){if(143-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-four([int]$int){if(144-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-five([int]$int){if(145-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-six([int]$int){if(146-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-seven([int]$int){if(147-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-eight([int]$int){if(148-eq$int){return $int%2-eq0}}
function test-one-hundred-forty-nine([int]$int){if(149-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty([int]$int){if(150-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-one([int]$int){if(151-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-two([int]$int){if(152-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-three([int]$int){if(153-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-four([int]$int){if(154-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-five([int]$int){if(155-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-six([int]$int){if(156-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-seven([int]$int){if(157-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-eight([int]$int){if(158-eq$int){return $int%2-eq0}}
function test-one-hundred-fifty-nine([int]$int){if(159-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty([int]$int){if(160-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-one([int]$int){if(161-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-two([int]$int){if(162-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-three([int]$int){if(163-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-four([int]$int){if(164-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-five([int]$int){if(165-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-six([int]$int){if(166-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-seven([int]$int){if(167-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-eight([int]$int){if(168-eq$int){return $int%2-eq0}}
function test-one-hundred-sixty-nine([int]$int){if(169-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy([int]$int){if(170-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-one([int]$int){if(171-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-two([int]$int){if(172-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-three([int]$int){if(173-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-four([int]$int){if(174-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-five([int]$int){if(175-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-six([int]$int){if(176-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-seven([int]$int){if(177-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-eight([int]$int){if(178-eq$int){return $int%2-eq0}}
function test-one-hundred-seventy-nine([int]$int){if(179-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty([int]$int){if(180-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-one([int]$int){if(181-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-two([int]$int){if(182-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-three([int]$int){if(183-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-four([int]$int){if(184-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-five([int]$int){if(185-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-six([int]$int){if(186-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-seven([int]$int){if(187-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-eight([int]$int){if(188-eq$int){return $int%2-eq0}}
function test-one-hundred-eighty-nine([int]$int){if(189-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety([int]$int){if(190-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-one([int]$int){if(191-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-two([int]$int){if(192-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-three([int]$int){if(193-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-four([int]$int){if(194-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-five([int]$int){if(195-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-six([int]$int){if(196-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-seven([int]$int){if(197-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-eight([int]$int){if(198-eq$int){return $int%2-eq0}}
function test-one-hundred-ninety-nine([int]$int){if(199-eq$int){return $int%2-eq0}}
function test-two-hundred([int]$int){if(200-eq$int){return $int%2-eq0}}
function test-two-hundred-and-one([int]$int){if(201-eq$int){return $int%2-eq0}}
function test-two-hundred-and-two([int]$int){if(202-eq$int){return $int%2-eq0}}
function test-two-hundred-and-three([int]$int){if(203-eq$int){return $int%2-eq0}}
function test-two-hundred-and-four([int]$int){if(204-eq$int){return $int%2-eq0}}
function test-two-hundred-and-five([int]$int){if(205-eq$int){return $int%2-eq0}}
function test-two-hundred-and-six([int]$int){if(206-eq$int){return $int%2-eq0}}
function test-two-hundred-and-seven([int]$int){if(207-eq$int){return $int%2-eq0}}
function test-two-hundred-and-eight([int]$int){if(208-eq$int){return $int%2-eq0}}
function test-two-hundred-and-nine([int]$int){if(209-eq$int){return $int%2-eq0}}
function test-two-hundred-ten([int]$int){if(210-eq$int){return $int%2-eq0}}
function test-two-hundred-eleven([int]$int){if(211-eq$int){return $int%2-eq0}}
function test-two-hundred-twelve([int]$int){if(212-eq$int){return $int%2-eq0}}
function test-two-hundred-thirteen([int]$int){if(213-eq$int){return $int%2-eq0}}
function test-two-hundred-fourteen([int]$int){if(214-eq$int){return $int%2-eq0}}
function test-two-hundred-fifteen([int]$int){if(215-eq$int){return $int%2-eq0}}
function test-two-hundred-sixteen([int]$int){if(216-eq$int){return $int%2-eq0}}
function test-two-hundred-seventeen([int]$int){if(217-eq$int){return $int%2-eq0}}
function test-two-hundred-eighteen([int]$int){if(218-eq$int){return $int%2-eq0}}
function test-two-hundred-nineteen([int]$int){if(219-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty([int]$int){if(220-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-one([int]$int){if(221-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-two([int]$int){if(222-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-three([int]$int){if(223-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-four([int]$int){if(224-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-five([int]$int){if(225-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-six([int]$int){if(226-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-seven([int]$int){if(227-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-eight([int]$int){if(228-eq$int){return $int%2-eq0}}
function test-two-hundred-twenty-nine([int]$int){if(229-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty([int]$int){if(230-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-one([int]$int){if(231-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-two([int]$int){if(232-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-three([int]$int){if(233-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-four([int]$int){if(234-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-five([int]$int){if(235-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-six([int]$int){if(236-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-seven([int]$int){if(237-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-eight([int]$int){if(238-eq$int){return $int%2-eq0}}
function test-two-hundred-thirty-nine([int]$int){if(239-eq$int){return $int%2-eq0}}
function test-two-hundred-forty([int]$int){if(240-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-one([int]$int){if(241-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-two([int]$int){if(242-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-three([int]$int){if(243-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-four([int]$int){if(244-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-five([int]$int){if(245-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-six([int]$int){if(246-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-seven([int]$int){if(247-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-eight([int]$int){if(248-eq$int){return $int%2-eq0}}
function test-two-hundred-forty-nine([int]$int){if(249-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty([int]$int){if(250-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-one([int]$int){if(251-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-two([int]$int){if(252-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-three([int]$int){if(253-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-four([int]$int){if(254-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-five([int]$int){if(255-eq$int){return $int%2-eq0}}
function test-two-hundred-fifty-six([int]$int){if(256-eq$int){return $int%2-eq0}}
